pacocoursey/cmdk

website/components/cmdk/raycast.tsx
Fixes focusing the address bar in Firefox.
=> Prevent default on Raycast submenu

website/styles/index.module.scss
This prevents the button contents from shifting during transforms
=> Add will-change property to buttons

README.md, cmdk/src/index.tsx, package.json, playwright.config.ts, test/group.test.ts, test/package.json, website/styles/cmdk/raycast.scss, website/styles/cmdk/vercel.scss
Fixes #26 
I risked this change in [c95c9a0](https://github.com/pacocoursey/cmdk/pull/1/commits/c95c9a0f77173600c99d78af45b9d5ca40053355) but didn't realize each item would be remounted with a new id when the group is hidden, which breaks a lot of logic that relies on each item having a stable id.
=> Use [hidden] on group instead of changing render structure

.github/workflows/test.yml, .gitignore, cmdk/src/index.tsx, playwright.config.ts
Closes https://github.com/pacocoursey/cmdk/issues/30 & https://github.com/pacocoursey/cmdk/issues/24 (https://github.com/pacocoursey/cmdk/pull/25)
=> Fix group filtering

README.md
Might want to remove the dollar sign from the `$ npm install cmdk` code snippet since using the copy button next to it copies the whole thing into clipboard which causes errors when pasting into terminals
=> remove dollar sign from code snippet

cmdk/src/index.tsx, test/keybind.test.ts, test/pages/keybinds.tsx
This fixes a bug where if the first Item is `disabled`, <kbd>⌘</kbd>+<kbd>↓</kbd> does not focus the _last_ valid item.
=> fix(keybinds): `last` fn respects disabled items

README.md, cmdk/src/index.tsx
Allows the arrow keys to wrap around, so when you press "up" from the input you end up at the bottom item, and when you press down while the last item is selected, it wraps around back to the first item in the list.
Fixes #56.
=> arrow keys wrap around

README.md, cmdk/src/index.tsx
This adds the option to set a `container` prop to `Command.Dialog` that tells `RadixDialog.Portal` to render into a specific element, rather than `body`.
=> Allow setting a container for Radix.Portal

cmdk/src/index.tsx
Hopefully should fix #64
As stated in the WICG discussion, the workaround to prevent the infinite loops is to call the observer logic within the [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame). 
So, this changeset do just that and adds `cancelAnimationFrame` call to the observer cleanup phase.
Since I'm not sure how to reproduce this locally I have only run the existing tests and launched website locally to confirm that I cannot spot any regression.
=> fix: attempt to prevent exceeding ResizeObserver loop limit

cmdk/src/index.tsx
=> fix: call `onValueChange` after filtering the list

.github/workflows/test.yml, playwright.config.ts
Assuming we want JSON output for Playwright test results. Set up [multiple reporters](https://playwright.dev/docs/test-reporters#multiple-reporters). Also added an `exit 1` if tests fail so if the `pnpm test` step fails (i.e., tests fail), it will exit with a non-zero status code, which will cause the entire job to fail.
Related: https://github.com/pacocoursey/cmdk/issues/24, https://github.com/pacocoursey/cmdk/pull/25
---
Thanks for the work and setting up such a clean organized project @pacocoursey @raunofreiberg
=> Fix Playwright Tests

cmdk/package.json, cmdk/src/index.tsx
I love this library, but I'm using it in a Chakra UI project and I don't need to extra weight of the radix ui dialog (9.5kb)
By exporting all individual components everything except Dialog can be imported, allowing bundlers to treeshake unused code and dependencies.
=> feat: export individual components to allow for tree shaking

cmdk/src/index.tsx, test/props.test.ts
In the code it is checked if `value !== undefined` to call `onValueChange`, so when no item is selected the value is `undefined` making the `Command` uncontrolled.
Closes #106
=> Fix controlled item value

cmdk/src/index.tsx
- Add `aria-activedescendant` to announce items to screen readers
Closes #92
=> feat: add `aria-activedescendant` in input

cmdk/src/index.tsx, test/pages/props.tsx, test/props.test.ts
Fixes that cmdk always focus on the first item even if another item value is provided.
Closes #90
=> fix: keep focus on the initial value

README.md, cmdk/src/index.tsx, website/styles/cmdk/framer.scss, website/styles/cmdk/linear.scss, website/styles/cmdk/raycast.scss, website/styles/cmdk/vercel.scss
Following what was said in #77 I believe it should also apply to `aria-disabled` and for consistency. This PR adds:
- Add `data-disabled` attribute to `Item` part
- Update docs and examples to recommend using `data-attributes` instead of `aria-attributes`
=> Add `data-disabled` to `Item` and recommend using data attributes

cmdk/src/index.tsx, website/components/cmdk/raycast.tsx
Closes #115 
In this PR, I added the optional prop of default value, which, when passing the item's value to the default value, makes this item active. Otherwise, the function of activating the first item on the list continues.
```tsx
const [value, setValue] = React.useState('apple')
return (
<Command value={value} onValueChange={setValue}>
<Command.Input />
<Command.List>
<Command.Item>Orange</Command.Item>
<Command.Item>Apple</Command.Item>
</Command.List>
</Command>
)
```
```tsx
return (
<Command defaultValue="Apple">
<Command.Input />
<Command.List>
<Command.Item>Orange</Command.Item>
<Command.Item>Apple</Command.Item>
</Command.List>
</Command>
)
```
=> feat: add default value prop

cmdk/src/index.tsx
Currently, to force the rendering of the group and its items we must use `forceMount` on `Command.Group` and all of its `Command.Item` manually. 
This PR adds the group's `forceMount` as a fallback for items so it only needs to be defined in `Command.Group`.
=> chore: use forceMount from group as fallback

cmdk/src/index.tsx
Reverts pacocoursey/cmdk#84
This doesn't actually make any sense, oops. If `disable` or `selected` is false, we'd output `undefined`.
=> Revert "Fix: `selected` and `disabled` state"

cmdk/package.json, cmdk/src/command-score.ts, cmdk/src/index.tsx, pnpm-lock.yaml, test/numeric.test.ts, test/pages/numeric.tsx
=> Bring in local dependency of command-score

README.md
This PR adds links to the NPM page for `cmdk` in the two little package-related badges in the README title.
- Zip size badge goes to `npmjs.com/package/cmdk?activeTab=code` to show the published files
- NPM version badge goes to `npmjs.com/package/cmdk` to show the published package
=> Add links to title badges

cmdk/src/index.tsx, test/keybind.test.ts, test/pages/keybinds.tsx
On macs `ctrl+k` removes text from current cursor position to end of line. Several of our users have commented that they don't want us overriding this behavior. Add an option to turn it off.
=> Add option for disabling vim bindings

cmdk/src/index.tsx
This fixes a bug where backspacing would not properly reveal items that didn't have their `value` explicitly set.
@dschlabach identified the root cause of the issue in #172; this is just a tiny change to better retain the previously detected `value` in that function when the element no longer exists in the DOM.
=> Fix bug with backspacing

cmdk/src/index.tsx
resolve #222 
This commit https://github.com/pacocoursey/cmdk/commit/8aecf2d22c288872a3908ef3041a9279d5f29d60 missing another position that should escape quotes in `[data-value=...]`
=> fix: escape quote

cmdk/src/index.tsx
Exporting the `defaultFilter` would allow users to re-use the internal command-score implementation with their own wrapping function. For example, we might want to transform one or more of the arguments before calling it.
```js
import { Command, defaultFilter } from 'cmdx'
<Command 
filter={(value, search, keywords) => 
defaultFilter(value, search.replaceAll(' ', ''), keywords)
}
>
...
</Command>
```
=> feat: export defaultFilter

cmdk/package.json
Currently, the npm package doesn't link to the repo, so it's not straightforward to access the source code when you just installed the library. Also, dependabot updates currently do not link to the project.
| npm | dependabot |
| - | - |
| ![image](https://github.com/pacocoursey/cmdk/assets/4947671/e2edaad7-4a5c-486c-839d-e74c9b0cec7f)  | ![image](https://github.com/pacocoursey/cmdk/assets/4947671/4418797a-a758-4c0b-9d50-89bf084ab7c9) |
This is caused by missing properties in `cmdk`'s `package.json`. After adding these properties, the npm page would look something like this, providing easy access to the package's source.
**Question:**
- Should "Homepage" point to this repo or https://cmdk.paco.me?
=> chore: add more details to package.json

cmdk/src/index.tsx, test/pages/portal.tsx
when used as combobox (`Command.List` as popover) manually changing input value leads to "undefined is not iterable" error cause there is no "valid items" in DOM and array.from runs on undefined.
I succeded to reproduct it in Portal page and added there two buttons: hide `Command.List` (fake popover) and toggle search term. Wasnt sure if it should be added at Portal page or props page. Technically its not directly related to portal. Let me know if you want me to move it.
=> fix: controlled search change with hidden Command.List

website/components/cmdk/framer.tsx
The framer example on the cmdk website is not working. This is because the values from command items are capitalized while the value-checking rendering of components (Button, Input, Badge, etc.) is not capitalized.
=> fix: Framer example capitalization of values

cmdk/src/index.tsx
The compiled code of this function will break, since Array.from(void 0) will have error
=> fix: fix compiling code Array.from(void 0)

cmdk/package.json, cmdk/src/index.tsx, pnpm-lock.yaml
Projects not using react 18 are not able to use CMDK lib. #162 
This PR implements retro-compatibility for one of the hooks from React 18 used by the lib.
=> fix: useId backward compatibility

cmdk/package.json, pnpm-lock.yaml
This will help propagation of bug fixes or features (e.g. React 19 support).
If Radix UI frequently breaks semantic versioning, it should be avoided. Pinning packages to patch versions contributes to bundle size bloat.
=> Relax dependencies on Radix-UI to SemVer MAJOR releases

cmdk/package.json
I get the following warning from pnpm after upgrading to NextJS v15 (released today), which installs react 19 RC
React 19 is technically still in RC stage, but since a stable version of a major Metaframework is installing it, it's a sign that it's ready for production use and will now be used by many projects.
```
│ ├─┬ cmdk 1.0.0
│ │ ├── ✕ unmet peer react@^18.0.0: found 19.0.0-rc-65a56d0e-20241020
│ │ ├── ✕ unmet peer react-dom@^18.0.0: found 19.0.0-rc-65a56d0e-20241020
```
P.S.: thank you so much for this package! it has been a big source of inspiration for my project (radix UI for AI chat interfaces)
=> feat: allow react v19 as peer dep

.github/workflows/test.yml, cmdk/package.json, pnpm-lock.yaml
Right now, cmdk's version range doesn't permit react-id from getting upgrade to 1.1.x, and the 1.0.x release includes a dependency on `@babel/runtime`, which is a bit of a bummer and unnecessary ( see https://npmgraph.js.org/?q=cmdk ).
This upgrades that dependency, as well as the versions of the GitHub Actions.
=> Upgrade @radix-ui/react-id

cmdk/src/index.tsx
**Issue:**
At present, updating the value `disablePointerSelection` prop _after_ the component has rendered once does not propagate the updated value to the underlying code. `context` has outdated value of `disablePointerSelection` since the dependency array for `useMemo` is empty.
**Proposed Fix:**
Similar to other places in current codebase, use the `propsRef` which carries updated props instead of directly referencing `disablePointerSelection` prop.
=> fix(context): read disablePointerSelection from propsRef

cmdk/src/index.tsx
I think this is related to the most recent changes in 1.0.4. The return type of `useCommandState` became `any` which caused lint failures in our application. I assume it was a mistake.
**before this change**
**after this change**
=> fix useCmdk return type

cmdk/src/index.tsx
In #229, the `defaultFilter` was exported, but its type is [currently defined](https://github.com/pacocoursey/cmdk/blob/9827edf89fc663e24188f9d715a0dca01a736d6d/cmdk/src/index.tsx#L159) as `CommandProps['filter']`, [which is](https://github.com/pacocoursey/cmdk/blob/9827edf89fc663e24188f9d715a0dca01a736d6d/cmdk/src/index.tsx#L95):
```
filter?: (value: string, search: string, keywords?: string[]) => number;
```
This means the TypeScript compiler treats `defaultFilter` as a function or undefined. However, defaultFilter is intended always to be present.
This PR updates the type definition to ensure `defaultFilter` is consistently defined as a function, eliminating the (false 🤭 ) possibility of it being undefined.
=> fix: update the type of the defaultFilter

cmdk/src/index.tsx
This PR addresses a bug where key bindings were unintentionally triggered twice during IME (Input Method Editor) composition. The issue occurred because IME input events were not properly handled, leading to duplicate keybinding activations in certain scenarios.
When using an IME for text input (e.g., for languages like Korean, Japanese, or Chinese), the composition process generates intermediate key events. In the current implementation, these events were mistakenly causing the key binding logic to execute twice—once for the actual input and once for the intermediate composition event.
=> Fix unintended double triggering of key bindings during IME composition
